language: cpp

compiler: gcc

before_install:
    - sudo apt-get clean -qq
    - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -y gcc-4.9 g++-4.9
    - export CC="gcc-4.9"
    - export CXX="g++-4.9"
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
    - git clone https://github.com/mavam/libbf.git && cd libbf && ./configure && make && make install
    
script: 
    - cd kbf
    - make
    - make test
