language: cpp

compiler: gcc

before_install:
    - echo "yes" | sudo apt-add-repository ppa:boost-latest
    - echo "yes" | sudo apt-add-repository ppa:h-rayflood/gcc-upper
    - sudo apt-get clean -qq
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.7 g++-4.7
    - export CC="gcc-4.7"
    - export CXX="gcc-4.7"
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 50
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 50
    - git clone https://github.com/mavam/libbf.git && cd libbf && ./configure && make && make test && make install
    
script: 
    - cd kbf
    - make
    - make test
